#region Copyright
////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2017 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 20.38Release
// Tag = production/akw/20.38.00-0-geccbce3
////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile ExdDisplayType type as an enum
    /// </summary>
    public enum ExdDisplayType : byte
    {
        Numerical = 0,
        Simple = 1,
        Graph = 2,
        Bar = 3,
        CircleGraph = 4,
        VirtualPartner = 5,
        Balance = 6,
        StringList = 7,
        String = 8,
        SimpleDynamicIcon = 9,
        Gauge = 10,
        Invalid = 0xFF


    }
}

